[proxmox_hosts]
# Update hostnames / IPs below to match your Proxmox VE nodes:
proxmox01 ansible_host=192.168.1.25 ansible_user=root
# bulakan   ansible_host=192.168.1.26 ansible_user=root
# cebu      ansible_host=192.168.1.27 ansible_user=root

[proxmox_hosts:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
