name: "Terraform Proxmox CI/CD"

on:
  push:
    branches:
      - main
    paths:
      - "infra/proxmox/**"
  pull_request:
    paths:
      - "infra/proxmox/**"

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    # Using self-hosted homelab runner to have access to the internal Proxmox network (192.168.1.26)
    runs-on: self-hosted

    # Set the working directory to where our Proxmox Terraform code is located
    defaults:
      run:
        working-directory: infra/proxmox

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true
        env:
          # In your GitHub repository settings, go to Secrets and variables -> Actions
          # and add these secrets to match your Proxmox login details.
          TF_VAR_proxmox_endpoint: ${{ secrets.PROXMOX_VE_ENDPOINT }}
          TF_VAR_proxmox_username: ${{ secrets.PROXMOX_VE_USERNAME }}
          TF_VAR_proxmox_password: ${{ secrets.PROXMOX_VE_PASSWORD }}

      - name: Comment PR Outline
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`terraform\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>`;

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          TF_VAR_proxmox_endpoint: ${{ secrets.PROXMOX_VE_ENDPOINT }}
          TF_VAR_proxmox_username: ${{ secrets.PROXMOX_VE_USERNAME }}
          TF_VAR_proxmox_password: ${{ secrets.PROXMOX_VE_PASSWORD }}
